// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forms.Models
{
    public partial class ControlType
    {
        public ControlType()
        {
            FrmQuestions = new HashSet<FrmQuestions>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public string CssClass { get; set; }
        public string HtmlContent { get; set; }

        public virtual ICollection<FrmQuestions> FrmQuestions { get; set; }
    }
}