// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forms.Models
{
    public partial class DataSourceCtrl
    {
        public int Id { get; set; }
        public int? DataSourceId { get; set; }
        public int QuestionId { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual DataSources DataSource { get; set; }
        public virtual FrmQuestions Question { get; set; }
    }
}