// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forms.Models
{
    public partial class DataSources
    {
        public DataSources()
        {
            DataSourceCtrl = new HashSet<DataSourceCtrl>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual ICollection<DataSourceCtrl> DataSourceCtrl { get; set; }
    }
}