// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forms.Models
{
    public partial class FrmForms
    {
        public FrmForms()
        {
            FrmQuestions = new HashSet<FrmQuestions>();
        }

        public int Id { get; set; }
        public Guid? Guid { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public string DescriptionAr { get; set; }
        public string DescriptionEn { get; set; }
        public bool? RequiresLogin { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual ICollection<FrmQuestions> FrmQuestions { get; set; }
    }
}